### PR TITLE
install coveralls after success

### PR DESCRIPTION
**Pull request by therealmarv**
fix coveralls

### CODE REVIEW

**Comment by therealmarv** [comment]
there you are coveralls! :tshirt::jeans: :eyes:

**Comment by alejandrodob** [comment]
:cake:

**Comment by teleyinex** [comment]
What a stupid mistake, right? Why it was not working in the before section? :cake:

**Comment by therealmarv** [comment]
It has to do with the internals of how this docker Travis build works. I'm guessing something is cleared in the (virtual)env and docopt is missing after-success.

**Pull request merged**
