### PR TITLE
Issue privacy policy

### PR DESCRIPTION
**Pull request by teleyinex**

### CODE REVIEW

**Comment by teleyinex** [comment]
There are no tests yet. I'll add them once the basic theme is merged.

**Comment by alejandrodob** [comment]
does this need to be documented? I mean, somewhere we tell the users that if they want they can add their own privacy policy to by adding the corresponding template to the theme.

**Comment by teleyinex** [comment]
@alejandrodob I think so :-) The issue is that there are so many scenarios that we cannot provide a generic one. Thus it's up to the owners to check with their lawyers.

**Comment by alejandrodob** [comment]
:cake:

**Pull request merged**
